services:
  azure_web_app_vfs:
    build: .
    container_name: azure_web_app_vfs
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.azure_web_app_vfs.rule=Host(`azure_web_app_vfs.wrlc.localhost`)"
      - "traefik.http.routers.azure_web_app_vfs.tls=true"
      - "traefik.http.routers.azure_web_app_vfs.entrypoints=websecure"
    depends_on:
      - azure_web_app_vfs_db
    networks:
      - proxy

  azure_web_app_vfs_db :
    image: mariadb:latest
    container_name: azure_web_app_vfs_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3332:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - proxy

volumes:
    mysql-data:

networks:
  proxy:
    external: true
