#file: noinspection UndefinedAction,UndefinedParamsPresent
name: Flake8

on: push

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Install mariadb dependencies
      run: sudo apt install libmariadb3 libmariadb-dev

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instal Python dependencies
      run: pip install -r requirements.txt

    - name: Run flake8
      run: flake8 app/